name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml 

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libgtk-3-dev 
          flutter pub get 
      
      - name: Build for Linux 
        run: |
          flutter build linux --release
          mv build/linux/x64/release/bundle/freee_dakoku_flutter freee_dakoku_flutter_linux_${{ github.ref_name }}

      #- name: Build for Windows
      #  run: |
      #    flutter build windows --release
      #    cd build/windows/runner/Release
      #    zip -r ../../../../../freee_dakoku_flutter_windows_${{ github.ref_name }}.zip *.exe *.dll *.pdb *.manifest *.appx *.appxbundle
      #    cd ../../../../../
      
      #- name: Build for MacOS
      #  run: |
      #    flutter build macos --release
      #    cd build/macos/Build/Products/Release
      #    zip -r ../../../../../freee_dakoku_flutter_macos_${{ github.ref_name }}.zip *.app
      #    cd ../../../../../

      - name: Create Release
        run: |
          gh release create ${{github.ref_name}} --generate-notes freee_dakoku_flutter_linux_${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      # Add additional assets upload steps for other platforms here if needed